### ISSUE TITLE
Aot Not Supported using angular 5 Calling function 'ɵmakeDecorator', function calls are not supported.

### ISSUE THREAD

**Issue by hazeem1991** [qligier/angular4-events#3] opened 2018-03-18 03:02 UTC
I added this plugin but when i try to build with aot the it crashes

**Comment by Gutto1** [comment] 2018-03-29 18:20
I am having the same issue when I run the 'ng build --prod' command. The message that is shown is:
```
ERROR in angular4-events/esm/src/angular4-events.module.ts(4,2): Error during template compile of 'EventsModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'
```

**Comment by qligier** [comment] 2018-03-29 19:42
Please check you have the latest version of the plugin if using Angular 5: `npm install --save angular4-events@latest`.
I can reproduce a similar error with Angular 5 and _angular4-events@4.0.1_ but not with _angular4-events@5.0.0_.

**Comment by lsvih** [comment] 2018-03-30 01:19
angular/cli@1.7.2, angular/core@5.2.0 and angular4-events@5.0.0, couldn't reproduce this problem

**Comment by qligier** [comment] 2018-06-18 08:58
Closing this issue as I could not reproduce it. If issue arises again, please don't hesitate to open a new issue with a complete description of it, thanks.

**Closed by qligier** 2018-06-18 08:58 UTC
Labels: question
